dbfilename redis_queue.rdb
dir /home/mohamed/my_bench/config/pids
pidfile /home/mohamed/my_bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/mohamed/my_bench/config/redis_queue.acl
